package es.upm.etsisi.poo.Actions.TicketHandlerActions;

import es.upm.etsisi.poo.Actions.Action;
import es.upm.etsisi.poo.App;

public class AddNewTicket extends Action {
    public AddNewTicket(App app) {
        super(app);
    }

    @Override
    public int execute(String[] args) {
        String ticketId = null;
        String cashId;
        String customerId;

        if (args.length == 2) {
            cashId = args[0];
            customerId = args[1];
            ticketId = null; // Se generará automáticamente en TicketBook
        } else if (args.length == 3) {
            ticketId = args[0];
            cashId = args[1];
            customerId = args[2];
        } else {
            System.err.println("ERROR: Two or three arguments are required: [<ticketId>] <cashId> <customerId>.");
            return -1;
        }

        int result = app.tickets.addNewTicket(app, ticketId, cashId, customerId);

        if (result == 0) {

            String finalTicketId = (ticketId == null || ticketId.isEmpty()) ? "autogenerated" : ticketId;

            System.out.println("Ticket with ID: '" + finalTicketId + "' created successfully for cashier with ID: '" + cashId + "'.");
            return 0;
        } else if (result == -1) {
            System.err.println("ERROR: Ticket with ID '" + ticketId + "' already exists.");
            return -2;
        } else {
            System.err.println("ERROR: Unknown error occurred.");
            return -3;
        }
    }

    @Override
    public String help() {
        return "ticket new [<ticketId>] <cashId> <customerId>: Creates a new ticket associated with a cashier and a customer. <ticketId> is optional.";
    }
}